#!/usr/bin/env bash
# This script displays the username, user ID, and home directory path from /etc/passwd.

while IFS=: read -r username _ userID _ _ _ homeDir _; do
  echo "$username:$userID:$homeDir"
done < /etc/passwd
